<?php
/**
 * OrderLine
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\KlarnaOrderManagementApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Vismutx\KlarnaOrderManagementApiPhp\Model;

use \ArrayAccess;
use \Vismutx\KlarnaOrderManagementApiPhp\ObjectSerializer;

/**
 * OrderLine Class Doc Comment
 *
 * @category Class
 * @package  Vismutx\KlarnaOrderManagementApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderLine implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'order_line';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'reference' => 'string',
        'type' => 'string',
        'quantity' => 'int',
        'quantity_unit' => 'string',
        'name' => 'string',
        'total_amount' => 'int',
        'unit_price' => 'int',
        'total_discount_amount' => 'int',
        'tax_rate' => 'int',
        'total_tax_amount' => 'int',
        'merchant_data' => 'string',
        'product_url' => 'string',
        'image_url' => 'string',
        'product_identifiers' => '\Vismutx\KlarnaOrderManagementApiPhp\Model\ProductIdentifiers'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'reference' => null,
        'type' => null,
        'quantity' => 'int64',
        'quantity_unit' => null,
        'name' => null,
        'total_amount' => 'int64',
        'unit_price' => 'int64',
        'total_discount_amount' => 'int64',
        'tax_rate' => 'int32',
        'total_tax_amount' => 'int64',
        'merchant_data' => null,
        'product_url' => null,
        'image_url' => null,
        'product_identifiers' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'reference' => 'reference',
        'type' => 'type',
        'quantity' => 'quantity',
        'quantity_unit' => 'quantity_unit',
        'name' => 'name',
        'total_amount' => 'total_amount',
        'unit_price' => 'unit_price',
        'total_discount_amount' => 'total_discount_amount',
        'tax_rate' => 'tax_rate',
        'total_tax_amount' => 'total_tax_amount',
        'merchant_data' => 'merchant_data',
        'product_url' => 'product_url',
        'image_url' => 'image_url',
        'product_identifiers' => 'product_identifiers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'reference' => 'setReference',
        'type' => 'setType',
        'quantity' => 'setQuantity',
        'quantity_unit' => 'setQuantityUnit',
        'name' => 'setName',
        'total_amount' => 'setTotalAmount',
        'unit_price' => 'setUnitPrice',
        'total_discount_amount' => 'setTotalDiscountAmount',
        'tax_rate' => 'setTaxRate',
        'total_tax_amount' => 'setTotalTaxAmount',
        'merchant_data' => 'setMerchantData',
        'product_url' => 'setProductUrl',
        'image_url' => 'setImageUrl',
        'product_identifiers' => 'setProductIdentifiers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'reference' => 'getReference',
        'type' => 'getType',
        'quantity' => 'getQuantity',
        'quantity_unit' => 'getQuantityUnit',
        'name' => 'getName',
        'total_amount' => 'getTotalAmount',
        'unit_price' => 'getUnitPrice',
        'total_discount_amount' => 'getTotalDiscountAmount',
        'tax_rate' => 'getTaxRate',
        'total_tax_amount' => 'getTotalTaxAmount',
        'merchant_data' => 'getMerchantData',
        'product_url' => 'getProductUrl',
        'image_url' => 'getImageUrl',
        'product_identifiers' => 'getProductIdentifiers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['reference'] = isset($data['reference']) ? $data['reference'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['quantity'] = isset($data['quantity']) ? $data['quantity'] : null;
        $this->container['quantity_unit'] = isset($data['quantity_unit']) ? $data['quantity_unit'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['total_amount'] = isset($data['total_amount']) ? $data['total_amount'] : null;
        $this->container['unit_price'] = isset($data['unit_price']) ? $data['unit_price'] : null;
        $this->container['total_discount_amount'] = isset($data['total_discount_amount']) ? $data['total_discount_amount'] : null;
        $this->container['tax_rate'] = isset($data['tax_rate']) ? $data['tax_rate'] : null;
        $this->container['total_tax_amount'] = isset($data['total_tax_amount']) ? $data['total_tax_amount'] : null;
        $this->container['merchant_data'] = isset($data['merchant_data']) ? $data['merchant_data'] : null;
        $this->container['product_url'] = isset($data['product_url']) ? $data['product_url'] : null;
        $this->container['image_url'] = isset($data['image_url']) ? $data['image_url'] : null;
        $this->container['product_identifiers'] = isset($data['product_identifiers']) ? $data['product_identifiers'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['reference']) && (mb_strlen($this->container['reference']) > 255)) {
            $invalidProperties[] = "invalid value for 'reference', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['reference']) && (mb_strlen($this->container['reference']) < 0)) {
            $invalidProperties[] = "invalid value for 'reference', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['type']) && !preg_match("/physical|discount|shipping_fee|sales_tax|store_credit|gift_card|digital|surcharge|return_fee/", $this->container['type'])) {
            $invalidProperties[] = "invalid value for 'type', must be conform to the pattern /physical|discount|shipping_fee|sales_tax|store_credit|gift_card|digital|surcharge|return_fee/.";
        }

        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if (($this->container['quantity'] < 0)) {
            $invalidProperties[] = "invalid value for 'quantity', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['quantity_unit']) && (mb_strlen($this->container['quantity_unit']) > 10)) {
            $invalidProperties[] = "invalid value for 'quantity_unit', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['quantity_unit']) && (mb_strlen($this->container['quantity_unit']) < 0)) {
            $invalidProperties[] = "invalid value for 'quantity_unit', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['name']) < 0)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['total_amount'] === null) {
            $invalidProperties[] = "'total_amount' can't be null";
        }
        if (($this->container['total_amount'] > 100000000)) {
            $invalidProperties[] = "invalid value for 'total_amount', must be smaller than or equal to 100000000.";
        }

        if ($this->container['unit_price'] === null) {
            $invalidProperties[] = "'unit_price' can't be null";
        }
        if (($this->container['unit_price'] > 100000000)) {
            $invalidProperties[] = "invalid value for 'unit_price', must be smaller than or equal to 100000000.";
        }

        if (!is_null($this->container['total_discount_amount']) && ($this->container['total_discount_amount'] > 100000000)) {
            $invalidProperties[] = "invalid value for 'total_discount_amount', must be smaller than or equal to 100000000.";
        }

        if (!is_null($this->container['total_discount_amount']) && ($this->container['total_discount_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'total_discount_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['tax_rate']) && ($this->container['tax_rate'] < 0)) {
            $invalidProperties[] = "invalid value for 'tax_rate', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['total_tax_amount']) && ($this->container['total_tax_amount'] > 100000000)) {
            $invalidProperties[] = "invalid value for 'total_tax_amount', must be smaller than or equal to 100000000.";
        }

        if (!is_null($this->container['merchant_data']) && (mb_strlen($this->container['merchant_data']) > 1024)) {
            $invalidProperties[] = "invalid value for 'merchant_data', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['merchant_data']) && (mb_strlen($this->container['merchant_data']) < 0)) {
            $invalidProperties[] = "invalid value for 'merchant_data', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['product_url']) && (mb_strlen($this->container['product_url']) > 1024)) {
            $invalidProperties[] = "invalid value for 'product_url', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['product_url']) && (mb_strlen($this->container['product_url']) < 0)) {
            $invalidProperties[] = "invalid value for 'product_url', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['image_url']) && (mb_strlen($this->container['image_url']) > 1024)) {
            $invalidProperties[] = "invalid value for 'image_url', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['image_url']) && (mb_strlen($this->container['image_url']) < 0)) {
            $invalidProperties[] = "invalid value for 'image_url', the character length must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets reference
     *
     * @return string
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string $reference Article number, SKU or similar.
     *
     * @return $this
     */
    public function setReference($reference)
    {
        if (!is_null($reference) && (mb_strlen($reference) > 255)) {
            throw new \InvalidArgumentException('invalid length for $reference when calling OrderLine., must be smaller than or equal to 255.');
        }
        if (!is_null($reference) && (mb_strlen($reference) < 0)) {
            throw new \InvalidArgumentException('invalid length for $reference when calling OrderLine., must be bigger than or equal to 0.');
        }

        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Order line type. Matches: physical|discount|shipping_fee|sales_tax|store_credit|gift_card|digital|surcharge|return_fee
     *
     * @return $this
     */
    public function setType($type)
    {

        if (!is_null($type) && (!preg_match("/physical|discount|shipping_fee|sales_tax|store_credit|gift_card|digital|surcharge|return_fee/", $type))) {
            throw new \InvalidArgumentException("invalid value for $type when calling OrderLine., must conform to the pattern /physical|discount|shipping_fee|sales_tax|store_credit|gift_card|digital|surcharge|return_fee/.");
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int $quantity Item quantity. Non-negative.
     *
     * @return $this
     */
    public function setQuantity($quantity)
    {

        if (($quantity < 0)) {
            throw new \InvalidArgumentException('invalid value for $quantity when calling OrderLine., must be bigger than or equal to 0.');
        }

        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets quantity_unit
     *
     * @return string
     */
    public function getQuantityUnit()
    {
        return $this->container['quantity_unit'];
    }

    /**
     * Sets quantity_unit
     *
     * @param string $quantity_unit Unit used to describe the quantity. Maximum 10 characters.
     *
     * @return $this
     */
    public function setQuantityUnit($quantity_unit)
    {
        if (!is_null($quantity_unit) && (mb_strlen($quantity_unit) > 10)) {
            throw new \InvalidArgumentException('invalid length for $quantity_unit when calling OrderLine., must be smaller than or equal to 10.');
        }
        if (!is_null($quantity_unit) && (mb_strlen($quantity_unit) < 0)) {
            throw new \InvalidArgumentException('invalid length for $quantity_unit when calling OrderLine., must be bigger than or equal to 0.');
        }

        $this->container['quantity_unit'] = $quantity_unit;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Descriptive item name. Maximum 255 characters.
     *
     * @return $this
     */
    public function setName($name)
    {
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling OrderLine., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($name) < 0)) {
            throw new \InvalidArgumentException('invalid length for $name when calling OrderLine., must be bigger than or equal to 0.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets total_amount
     *
     * @return int
     */
    public function getTotalAmount()
    {
        return $this->container['total_amount'];
    }

    /**
     * Sets total_amount
     *
     * @param int $total_amount Total amount including tax and discounts (`quantity * unit_price - total_discount_amount`).
     *
     * @return $this
     */
    public function setTotalAmount($total_amount)
    {

        if (($total_amount > 100000000)) {
            throw new \InvalidArgumentException('invalid value for $total_amount when calling OrderLine., must be smaller than or equal to 100000000.');
        }

        $this->container['total_amount'] = $total_amount;

        return $this;
    }

    /**
     * Gets unit_price
     *
     * @return int
     */
    public function getUnitPrice()
    {
        return $this->container['unit_price'];
    }

    /**
     * Sets unit_price
     *
     * @param int $unit_price Unit price including tax without applying discounts in minor units.
     *
     * @return $this
     */
    public function setUnitPrice($unit_price)
    {

        if (($unit_price > 100000000)) {
            throw new \InvalidArgumentException('invalid value for $unit_price when calling OrderLine., must be smaller than or equal to 100000000.');
        }

        $this->container['unit_price'] = $unit_price;

        return $this;
    }

    /**
     * Gets total_discount_amount
     *
     * @return int
     */
    public function getTotalDiscountAmount()
    {
        return $this->container['total_discount_amount'];
    }

    /**
     * Sets total_discount_amount
     *
     * @param int $total_discount_amount The discount amount in minor units. Includes tax. Example: 1200 = $12. Max value: 100000000
     *
     * @return $this
     */
    public function setTotalDiscountAmount($total_discount_amount)
    {

        if (!is_null($total_discount_amount) && ($total_discount_amount > 100000000)) {
            throw new \InvalidArgumentException('invalid value for $total_discount_amount when calling OrderLine., must be smaller than or equal to 100000000.');
        }
        if (!is_null($total_discount_amount) && ($total_discount_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $total_discount_amount when calling OrderLine., must be bigger than or equal to 0.');
        }

        $this->container['total_discount_amount'] = $total_discount_amount;

        return $this;
    }

    /**
     * Gets tax_rate
     *
     * @return int
     */
    public function getTaxRate()
    {
        return $this->container['tax_rate'];
    }

    /**
     * Sets tax_rate
     *
     * @param int $tax_rate The tax rate in percent with two implicit decimals. Non-negative. Example: 2500 = 25%.
     *
     * @return $this
     */
    public function setTaxRate($tax_rate)
    {

        if (!is_null($tax_rate) && ($tax_rate < 0)) {
            throw new \InvalidArgumentException('invalid value for $tax_rate when calling OrderLine., must be bigger than or equal to 0.');
        }

        $this->container['tax_rate'] = $tax_rate;

        return $this;
    }

    /**
     * Gets total_tax_amount
     *
     * @return int
     */
    public function getTotalTaxAmount()
    {
        return $this->container['total_tax_amount'];
    }

    /**
     * Sets total_tax_amount
     *
     * @param int $total_tax_amount The total tax amount in minor units. Negative if the order line type is discount. Example: 500 = $5.
     *
     * @return $this
     */
    public function setTotalTaxAmount($total_tax_amount)
    {

        if (!is_null($total_tax_amount) && ($total_tax_amount > 100000000)) {
            throw new \InvalidArgumentException('invalid value for $total_tax_amount when calling OrderLine., must be smaller than or equal to 100000000.');
        }

        $this->container['total_tax_amount'] = $total_tax_amount;

        return $this;
    }

    /**
     * Gets merchant_data
     *
     * @return string
     */
    public function getMerchantData()
    {
        return $this->container['merchant_data'];
    }

    /**
     * Sets merchant_data
     *
     * @param string $merchant_data Data about the order line. Set at creation or update and returned when fetching the order through the API. Maximum 1024 characters.
     *
     * @return $this
     */
    public function setMerchantData($merchant_data)
    {
        if (!is_null($merchant_data) && (mb_strlen($merchant_data) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $merchant_data when calling OrderLine., must be smaller than or equal to 1024.');
        }
        if (!is_null($merchant_data) && (mb_strlen($merchant_data) < 0)) {
            throw new \InvalidArgumentException('invalid length for $merchant_data when calling OrderLine., must be bigger than or equal to 0.');
        }

        $this->container['merchant_data'] = $merchant_data;

        return $this;
    }

    /**
     * Gets product_url
     *
     * @return string
     */
    public function getProductUrl()
    {
        return $this->container['product_url'];
    }

    /**
     * Sets product_url
     *
     * @param string $product_url URL to the product that can be used in communications between Klarna and the customer. Maximum 1024 characters.
     *
     * @return $this
     */
    public function setProductUrl($product_url)
    {
        if (!is_null($product_url) && (mb_strlen($product_url) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $product_url when calling OrderLine., must be smaller than or equal to 1024.');
        }
        if (!is_null($product_url) && (mb_strlen($product_url) < 0)) {
            throw new \InvalidArgumentException('invalid length for $product_url when calling OrderLine., must be bigger than or equal to 0.');
        }

        $this->container['product_url'] = $product_url;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string $image_url URL to an image that can be embedded in communications between Klarna and the customer. Maximum 1024 characters.
     *
     * @return $this
     */
    public function setImageUrl($image_url)
    {
        if (!is_null($image_url) && (mb_strlen($image_url) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $image_url when calling OrderLine., must be smaller than or equal to 1024.');
        }
        if (!is_null($image_url) && (mb_strlen($image_url) < 0)) {
            throw new \InvalidArgumentException('invalid length for $image_url when calling OrderLine., must be bigger than or equal to 0.');
        }

        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets product_identifiers
     *
     * @return \Vismutx\KlarnaOrderManagementApiPhp\Model\ProductIdentifiers
     */
    public function getProductIdentifiers()
    {
        return $this->container['product_identifiers'];
    }

    /**
     * Sets product_identifiers
     *
     * @param \Vismutx\KlarnaOrderManagementApiPhp\Model\ProductIdentifiers $product_identifiers Identifiers to better describe the product for improved risk assessment, support, presentation to consumers and promotional functionality.
     *
     * @return $this
     */
    public function setProductIdentifiers($product_identifiers)
    {
        $this->container['product_identifiers'] = $product_identifiers;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


