<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\KlarnaOrderManagementApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vismutx\KlarnaOrderManagementApiPhp;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class
 * @description Order
 * @package     Vismutx\KlarnaOrderManagementApiPhp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "fraud_status"
     */
    public function testPropertyFraudStatus()
    {
    }

    /**
     * Test attribute "order_amount"
     */
    public function testPropertyOrderAmount()
    {
    }

    /**
     * Test attribute "original_order_amount"
     */
    public function testPropertyOriginalOrderAmount()
    {
    }

    /**
     * Test attribute "captured_amount"
     */
    public function testPropertyCapturedAmount()
    {
    }

    /**
     * Test attribute "refunded_amount"
     */
    public function testPropertyRefundedAmount()
    {
    }

    /**
     * Test attribute "remaining_authorized_amount"
     */
    public function testPropertyRemainingAuthorizedAmount()
    {
    }

    /**
     * Test attribute "purchase_currency"
     */
    public function testPropertyPurchaseCurrency()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "order_lines"
     */
    public function testPropertyOrderLines()
    {
    }

    /**
     * Test attribute "merchant_reference1"
     */
    public function testPropertyMerchantReference1()
    {
    }

    /**
     * Test attribute "merchant_reference2"
     */
    public function testPropertyMerchantReference2()
    {
    }

    /**
     * Test attribute "klarna_reference"
     */
    public function testPropertyKlarnaReference()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "purchase_country"
     */
    public function testPropertyPurchaseCountry()
    {
    }

    /**
     * Test attribute "expires_at"
     */
    public function testPropertyExpiresAt()
    {
    }

    /**
     * Test attribute "captures"
     */
    public function testPropertyCaptures()
    {
    }

    /**
     * Test attribute "refunds"
     */
    public function testPropertyRefunds()
    {
    }

    /**
     * Test attribute "merchant_data"
     */
    public function testPropertyMerchantData()
    {
    }

    /**
     * Test attribute "initial_payment_method"
     */
    public function testPropertyInitialPaymentMethod()
    {
    }

    /**
     * Test attribute "selected_shipping_option"
     */
    public function testPropertySelectedShippingOption()
    {
    }
}
