<?php
/**
 * ShippingInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\KlarnaOrderManagementApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Vismutx\KlarnaOrderManagementApiPhp;

/**
 * ShippingInfoTest Class Doc Comment
 *
 * @category    Class
 * @description ShippingInfo
 * @package     Vismutx\KlarnaOrderManagementApiPhp
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingInfo"
     */
    public function testShippingInfo()
    {
    }

    /**
     * Test attribute "shipping_company"
     */
    public function testPropertyShippingCompany()
    {
    }

    /**
     * Test attribute "shipping_method"
     */
    public function testPropertyShippingMethod()
    {
    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {
    }

    /**
     * Test attribute "tracking_uri"
     */
    public function testPropertyTrackingUri()
    {
    }

    /**
     * Test attribute "return_shipping_company"
     */
    public function testPropertyReturnShippingCompany()
    {
    }

    /**
     * Test attribute "return_tracking_number"
     */
    public function testPropertyReturnTrackingNumber()
    {
    }

    /**
     * Test attribute "return_tracking_uri"
     */
    public function testPropertyReturnTrackingUri()
    {
    }
}
