<?php
/**
 * CapturesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\KlarnaOrderManagementApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Vismutx\KlarnaOrderManagementApiPhp;

use \Vismutx\KlarnaOrderManagementApiPhp\Configuration;
use \Vismutx\KlarnaOrderManagementApiPhp\ApiException;
use \Vismutx\KlarnaOrderManagementApiPhp\ObjectSerializer;

/**
 * CapturesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Vismutx\KlarnaOrderManagementApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CapturesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appendShippingInfo
     *
     * Add shipping info to a capture.
     *
     */
    public function testAppendShippingInfo()
    {
    }

    /**
     * Test case for captureOrder
     *
     * Create capture.
     *
     */
    public function testCaptureOrder()
    {
    }

    /**
     * Test case for extendDueDate
     *
     * Extend the customer's payment due date.
     *
     */
    public function testExtendDueDate()
    {
    }

    /**
     * Test case for getCapture
     *
     * Get capture.
     *
     */
    public function testGetCapture()
    {
    }

    /**
     * Test case for getCaptures
     *
     * Get all captures for one order.
     *
     */
    public function testGetCaptures()
    {
    }

    /**
     * Test case for getOptionsForExtendDueDate
     *
     * Get available options for extension of the customer's payment due date.
     *
     */
    public function testGetOptionsForExtendDueDate()
    {
    }

    /**
     * Test case for triggerSendOut
     *
     * Trigger resend of customer communication.
     *
     */
    public function testTriggerSendOut()
    {
    }
}
