<?php
/**
 * RefundsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Vismutx\KlarnaOrderManagementApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Vismutx\KlarnaOrderManagementApiPhp;

use \Vismutx\KlarnaOrderManagementApiPhp\Configuration;
use \Vismutx\KlarnaOrderManagementApiPhp\ApiException;
use \Vismutx\KlarnaOrderManagementApiPhp\ObjectSerializer;

/**
 * RefundsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Vismutx\KlarnaOrderManagementApiPhp
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RefundsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for get
     *
     * Get refund.
     *
     */
    public function testGet()
    {
    }

    /**
     * Test case for refundOrder
     *
     * Create a refund.
     *
     */
    public function testRefundOrder()
    {
    }
}
